"""initial_schema

Revision ID: 271611db7e9f
Revises:
Create Date: 2025-10-15 21:57:00.803296

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "271611db7e9f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
