name: Deploy to Staging

# Trigger strategies (choose one or combine):
# 1. Automatic: On push to develop branch (continuous staging deployment)
# 2. Manual: Via workflow_dispatch (on-demand staging deployment)
# 3. PR-based: On label 'deploy-to-staging' added to PR
on:
  # Strategy 1: Automatic deployment on develop branch push
  push:
    branches:
      - develop

  # Strategy 2: Manual deployment trigger
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to deploy (branch, tag, or SHA)'
        required: false
        default: 'develop'
      skip_tests:
        description: 'Skip validation tests (use with caution)'
        required: false
        type: boolean
        default: false

  # Strategy 3: PR-based deployment (when label added)
  pull_request:
    types:
      - labeled
    branches:
      - main

# Cancel in-progress staging deployments on new push
concurrency:
  group: staging-deployment
  cancel-in-progress: true

jobs:
  # Only run if triggered by push to develop, manual dispatch, or 'deploy-to-staging' label
  check-trigger:
    name: Validate Deployment Trigger
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check.outputs.deploy }}
    steps:
      - name: Check deployment conditions
        id: check
        run: |
          DEPLOY="false"

          # Allow push to develop
          if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            DEPLOY="true"
            echo "Trigger: Push to develop branch"
          fi

          # Allow manual workflow dispatch
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            DEPLOY="true"
            echo "Trigger: Manual workflow dispatch"
          fi

          # Allow PR with 'deploy-to-staging' label
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            LABELS='${{ toJSON(github.event.pull_request.labels.*.name) }}'
            if echo "$LABELS" | grep -q "deploy-to-staging"; then
              DEPLOY="true"
              echo "Trigger: PR labeled 'deploy-to-staging'"
            fi
          fi

          echo "deploy=$DEPLOY" >> $GITHUB_OUTPUT

          if [ "$DEPLOY" = "false" ]; then
            echo "❌ Deployment conditions not met - skipping"
          else
            echo "✅ Deployment conditions met - proceeding"
          fi

  # Run validation tests before staging deployment
  validate:
    name: Run Validation Tests
    runs-on: ubuntu-latest
    needs: check-trigger
    if: needs.check-trigger.outputs.should_deploy == 'true' && !inputs.skip_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Install dependencies
        run: |
          uv sync --all-extras --frozen

      - name: Run quick validation suite
        run: |
          echo "Running validation tests before staging deployment..."
          ~/.local/bin/task lint
          ~/.local/bin/task type-check
          ~/.local/bin/task test:unit

  # Build and push staging container image
  build-and-push:
    name: Build and Push Staging Container
    runs-on: ubuntu-latest
    needs: [check-trigger, validate]
    if: |
      always() &&
      needs.check-trigger.outputs.should_deploy == 'true' &&
      (needs.validate.result == 'success' || needs.validate.result == 'skipped')
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
      image_digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version and metadata
        id: meta
        run: |
          VERSION=$(grep '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)

          # Staging tag format: staging-v{version}-{timestamp}-{short-sha}
          STAGING_TAG="staging-v${VERSION}-${TIMESTAMP}-${SHORT_SHA}"

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "staging_tag=$STAGING_TAG" >> $GITHUB_OUTPUT
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

          echo "Staging Image Tags:"
          echo "  - ghcr.io/${{ github.repository }}:$STAGING_TAG"
          echo "  - ghcr.io/${{ github.repository }}:staging-latest"

      - name: Build and push staging container image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.staging_tag }}
            ghcr.io/${{ github.repository }}:staging-latest
          labels: |
            org.opencontainers.image.title=AI Agent MCP Server (Staging)
            org.opencontainers.image.description=Staging deployment of AI Agent MCP Server
            org.opencontainers.image.version=${{ steps.meta.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.meta.outputs.timestamp }}
            environment=staging
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image build summary
        run: |
          echo "✅ Staging container image built and pushed successfully"
          echo ""
          echo "**Registry:** ghcr.io/${{ github.repository }}"
          echo "**Tags:**"
          echo "  - ${{ steps.meta.outputs.staging_tag }}"
          echo "  - staging-latest"
          echo "**Digest:** ${{ steps.build.outputs.digest }}"
          echo "**Size:** $(docker images ghcr.io/${{ github.repository }}:staging-latest --format '{{.Size}}' 2>/dev/null || echo 'N/A')"

  # Security scan staging image
  security-scan:
    name: Scan Staging Container
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository }}:staging-latest'
          format: 'sarif'
          output: 'trivy-staging-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          exit-code: '0'  # Don't fail staging on vulnerabilities (warn only)
          ignore-unfixed: true
          trivyignores: '.trivyignore'

      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-staging-results.sarif'
          category: 'staging-container'

      - name: Security scan summary
        run: |
          echo "Security scan completed for staging image"
          echo "View results: https://github.com/${{ github.repository }}/security/code-scanning"

  # Optional: Deploy to staging environment (requires staging infrastructure)
  # Uncomment and configure based on your staging setup (Kubernetes, AWS, etc.)
  # deploy-to-environment:
  #   name: Deploy to Staging Environment
  #   runs-on: ubuntu-latest
  #   needs: [build-and-push, security-scan]
  #   environment:
  #     name: staging
  #     url: https://staging.example.com
  #   steps:
  #     - name: Deploy to staging
  #       run: |
  #         # Add deployment commands here
  #         # Examples:
  #         # - kubectl set image deployment/mcp-server mcp-server=ghcr.io/${{ github.repository }}:staging-latest
  #         # - aws ecs update-service --cluster staging --service mcp-server --force-new-deployment
  #         # - ssh staging-host "docker pull ghcr.io/${{ github.repository }}:staging-latest && docker-compose up -d"
  #         echo "Deploying to staging environment..."

  # Post-deployment validation (smoke tests)
  smoke-tests:
    name: Run Staging Smoke Tests
    runs-on: ubuntu-latest
    needs: build-and-push
    # Uncomment when deploy-to-environment is enabled:
    # needs: deploy-to-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for staging deployment
        run: |
          echo "Waiting for staging deployment to stabilize..."
          sleep 30

      # Option 1: Local smoke tests (run container locally)
      - name: Run local smoke tests
        run: |
          echo "Starting staging container for smoke tests..."

          # Pull staging image
          docker pull ghcr.io/${{ github.repository }}:staging-latest

          # Run container with test environment
          docker run -d \
            --name mcp-staging-smoke-test \
            -p 8000:8000 \
            -e APP_NAME="AI Agent MCP Server" \
            -e APP_VERSION="0.1.0" \
            -e DEBUG=false \
            -e HOST=0.0.0.0 \
            -e PORT=8000 \
            -e DATABASE_URL=postgresql+asyncpg://test:test@localhost:5432/test \
            -e LOG_LEVEL=INFO \
            -e LOG_FORMAT=json \
            ghcr.io/${{ github.repository }}:staging-latest

          # Wait for application to start
          sleep 10

          # Health check
          echo "Testing health endpoint..."
          HEALTH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health)

          if [ "$HEALTH_STATUS" = "200" ]; then
            echo "✅ Health check passed (HTTP $HEALTH_STATUS)"
          else
            echo "❌ Health check failed (HTTP $HEALTH_STATUS)"
            docker logs mcp-staging-smoke-test
            exit 1
          fi

          # Cleanup
          docker stop mcp-staging-smoke-test
          docker rm mcp-staging-smoke-test

      # Option 2: Remote smoke tests (test actual staging environment)
      # Uncomment and configure based on your staging URL
      # - name: Test staging environment
      #   run: |
      #     STAGING_URL="https://staging.example.com"
      #
      #     echo "Testing staging deployment at $STAGING_URL..."
      #
      #     # Health check
      #     HEALTH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" $STAGING_URL/health)
      #     if [ "$HEALTH_STATUS" != "200" ]; then
      #       echo "❌ Health check failed (HTTP $HEALTH_STATUS)"
      #       exit 1
      #     fi
      #
      #     echo "✅ Staging smoke tests passed"

  # Deployment summary and notification
  summary:
    name: Deployment Summary
    runs-on: ubuntu-latest
    needs: [build-and-push, security-scan, smoke-tests]
    if: always()
    steps:
      - name: Generate deployment summary
        run: |
          BUILD_STATUS="${{ needs.build-and-push.result }}"
          SCAN_STATUS="${{ needs.security-scan.result }}"
          SMOKE_STATUS="${{ needs.smoke-tests.result }}"

          if [ "$BUILD_STATUS" = "success" ] && [ "$SCAN_STATUS" = "success" ] && [ "$SMOKE_STATUS" = "success" ]; then
            echo "## ✅ Staging Deployment Successful" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Environment:** Staging" >> $GITHUB_STEP_SUMMARY
            echo "**Image:** ghcr.io/${{ github.repository }}:staging-latest" >> $GITHUB_STEP_SUMMARY
            echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "| Check | Status |" >> $GITHUB_STEP_SUMMARY
            echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
            echo "| Container Build | ✅ Success |" >> $GITHUB_STEP_SUMMARY
            echo "| Security Scan | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
            echo "| Smoke Tests | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
          else
            echo "## ❌ Staging Deployment Failed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "| Check | Status |" >> $GITHUB_STEP_SUMMARY
            echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
            echo "| Container Build | $( [ "$BUILD_STATUS" = "success" ] && echo '✅' || echo '❌' ) $BUILD_STATUS |" >> $GITHUB_STEP_SUMMARY
            echo "| Security Scan | $( [ "$SCAN_STATUS" = "success" ] && echo '✅' || echo '❌' ) $SCAN_STATUS |" >> $GITHUB_STEP_SUMMARY
            echo "| Smoke Tests | $( [ "$SMOKE_STATUS" = "success" ] && echo '✅' || echo '❌' ) $SMOKE_STATUS |" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      # Optional: Post to Slack/Discord/Teams
      # - name: Notify team
      #   if: always()
      #   run: |
      #     # Add notification logic here
      #     echo "Posting deployment notification..."
